# Generated by Django 6.0.6 on 2026-06-05 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, help_text='Desmarca si el producto no está a la venta.', verbose_name='Disponible'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Describe los detalles: material, medidas, cuidados.', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Sube la foto del producto. Se recomienda 600x600 px.', null=True, upload_to='products/', verbose_name='Foto principal'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre del producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Precio base del producto.', max_digits=10, verbose_name='Precio ($)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad disponible en inventario.', verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(choices=[('oro_18k', 'Oro 18K'), ('oro_rosa', 'Oro Rosa'), ('plata', 'Plata'), ('acero', 'Acero Quirúrgico')], default='oro_18k', max_length=50, verbose_name='Material')),
                ('color', models.CharField(choices=[('dorado', 'Dorado'), ('plateado', 'Plateado'), ('rosado', 'Rosado'), ('negro', 'Negro')], default='dorado', max_length=50, verbose_name='Color')),
                ('size', models.CharField(blank=True, help_text='Ej: 7 (anillo), 45 cm (collar), Única', max_length=50, verbose_name='Talla/Medida')),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Si está vacío, usa el precio del producto.', max_digits=10, null=True, verbose_name='Precio especial ($)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock de esta variante')),
                ('image', models.ImageField(blank=True, help_text='Opcional. Si no se sube, se usa la foto del producto.', null=True, upload_to='variants/', verbose_name='Foto de la variante')),
                ('sku', models.CharField(blank=True, help_text='Código interno del producto.', max_length=100, unique=True, verbose_name='SKU/Código')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Variante',
                'verbose_name_plural': 'Variantes',
                'unique_together': {('product', 'material', 'color', 'size')},
            },
        ),
    ]
