# Generated by Django 6.0.6 on 2026-06-21 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='Imagen adicional')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Texto alternativo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Imagen del producto',
                'verbose_name_plural': 'Imágenes del producto',
                'ordering': ['order'],
            },
        ),
    ]
